# Generated by Django 5.2.16 on 2026-07-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fixo", "Prova histórica completa"),
                            ("customizado", "Simulado customizado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="em_andamento",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulados",
                        to="accounts.alunoprofile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulados",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alternativa_escolhida", models.CharField(blank=True, max_length=1)),
                ("correta", models.BooleanField(null=True)),
                ("tempo_gasto_ms", models.PositiveIntegerField(default=0)),
                ("respondida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="accounts.alunoprofile",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respostas",
                        to="exams.question",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="simulados.simulado",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aluno_profile"], name="simulados_r_aluno_p_38c649_idx"
                    ),
                    models.Index(
                        fields=["simulado"], name="simulados_r_simulad_e556ea_idx"
                    ),
                    models.Index(
                        fields=["question"], name="simulados_r_questio_33a2c7_idx"
                    ),
                    models.Index(
                        fields=["respondida_em"], name="simulados_r_respond_144e92_idx"
                    ),
                ],
                "unique_together": {("simulado", "question")},
            },
        ),
        migrations.CreateModel(
            name="SimuladoQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="exams.question",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to="simulados.simulado",
                    ),
                ),
            ],
            options={
                "ordering": ["simulado", "ordem"],
                "unique_together": {("simulado", "question")},
            },
        ),
    ]
