# Generated by Django 5.2.16 on 2026-07-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("simulados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimuladoAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("prazo", models.DateTimeField(blank=True, null=True)),
                (
                    "alunos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simulado_assignments",
                        to="accounts.alunoprofile",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulado_assignments",
                        to="accounts.escola",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulado_assignments",
                        to="accounts.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulado_assignments",
                        to="accounts.turma",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="simulado",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulados",
                to="simulados.simuladoassignment",
            ),
        ),
    ]
