# Generated by Django 5.2.16 on 2026-07-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alunoprofile",
            name="assinatura_ativa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escola",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escolas",
                to="billing.plan",
            ),
        ),
    ]
