# Generated by Django 5.2.16 on 2026-07-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ciencias-humanas", "Ciências Humanas e suas Tecnologias"),
                            (
                                "ciencias-natureza",
                                "Ciências da Natureza e suas Tecnologias",
                            ),
                            ("linguagens", "Linguagens, Códigos e suas Tecnologias"),
                            ("matematica", "Matemática e suas Tecnologias"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["discipline", "name"],
                "unique_together": {("discipline", "name")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "external_index",
                    models.PositiveIntegerField(
                        help_text="Índice 1-183 da prova original"
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ciencias-humanas", "Ciências Humanas e suas Tecnologias"),
                            (
                                "ciencias-natureza",
                                "Ciências da Natureza e suas Tecnologias",
                            ),
                            ("linguagens", "Linguagens, Códigos e suas Tecnologias"),
                            ("matematica", "Matemática e suas Tecnologias"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("espanhol", "Espanhol"), ("ingles", "Inglês")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="Enunciado em markdown, pode referenciar imagens locais"
                    ),
                ),
                ("alternatives_introduction", models.TextField(blank=True)),
                ("correct_alternative", models.CharField(max_length=1)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="exams.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "external_index"],
                "unique_together": {("exam", "external_index", "language")},
            },
        ),
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                ("text", models.TextField(blank=True)),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "letter"],
                "unique_together": {("question", "letter")},
            },
        ),
    ]
