# Generated by Django 5.2.16 on 2026-07-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.FloatField(default=1.0)),
                ("b", models.FloatField()),
                ("c", models.FloatField()),
                (
                    "difficulty_source",
                    models.CharField(
                        choices=[
                            ("llm_estimate", "Estimativa do LLM"),
                            ("calibrated", "Calibrado via EM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("respondent_count", models.PositiveIntegerField(default=0)),
                ("last_calibrated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemparameters",
                        to="exams.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ciencias-humanas", "Ciências Humanas e suas Tecnologias"),
                            (
                                "ciencias-natureza",
                                "Ciências da Natureza e suas Tecnologias",
                            ),
                            ("linguagens", "Linguagens, Códigos e suas Tecnologias"),
                            ("matematica", "Matemática e suas Tecnologias"),
                        ],
                        max_length=32,
                    ),
                ),
                ("theta", models.FloatField(default=0.0)),
                ("theta_se", models.FloatField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cold_start", "Cold start"),
                            ("em_calibrated", "Calibrado via EM"),
                        ],
                        default="cold_start",
                        max_length=20,
                    ),
                ),
                (
                    "aluno_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilidades",
                        to="accounts.alunoprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno_profile", "discipline")},
            },
        ),
    ]
