# Generated by Django 5.2.16 on 2026-07-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("redacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaysubmission",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redacoes_corrigidas",
                to="accounts.professor",
            ),
        ),
        migrations.AddField(
            model_name="essaysubmission",
            name="foto",
            field=models.FileField(blank=True, null=True, upload_to="redacoes/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="essaysubmission",
            name="submission_type",
            field=models.CharField(
                choices=[("text", "Texto digitado"), ("photo", "Foto")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="essaysubmission",
            name="texto",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="EssayAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("tema", models.CharField(max_length=255)),
                ("texto_motivador", models.TextField(blank=True)),
                ("tema_gerado_por_ia", models.BooleanField(default=False)),
                (
                    "correction_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Correção manual pelo professor"),
                            ("ai", "Correção por IA"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prazo", models.DateTimeField(blank=True, null=True)),
                (
                    "alunos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="essay_assignments",
                        to="accounts.alunoprofile",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_assignments",
                        to="accounts.escola",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_assignments",
                        to="accounts.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essay_assignments",
                        to="accounts.turma",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="essaysubmission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissoes",
                to="redacao.essayassignment",
            ),
        ),
    ]
