# Generated by Django 5.2.16 on 2026-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("job_name", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em execução"),
                            ("success", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("triggered_by", models.CharField(default="manual", max_length=20)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
